services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    networks:
      - pmfr-network
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ${CAMINHO_PASTA_MYSQL}:/var/lib/mysql/
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf  # Arquivo de configuração personalizado
    healthcheck:  # Adicionado para verificar se o MySQL está pronto
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 30s                   # Aumentado para inicialização mais lenta
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    networks:
      - pmfr-network
    environment:
      - PMA_HOST=mysql  # Conecta ao container do MySQL pelo nome do serviço
      #- PMA_USER=${MYSQL_USER}  # Lê do db.env (ou defina diretamente aqui) //sem login automatico
      #- PMA_PASSWORD=${MYSQL_PASSWORD} //Sem login automatico

    depends_on:
      mysql:
        condition: service_healthy  # Só inicia após MySQL estar pronto
    restart: unless-stopped

networks:
  pmfr-network:
    external: true
